import cv2
import numpy as np
from ultralytics import YOLO
from datetime import datetime, timedelta
import time
import paho.mqtt.client as mqtt
from flask import Flask, Response, render_template_string
import threading
import json
import torch # Import torch to check for CUDA availability

# =========================
# CONFIGURATION
# =========================
IPCAM_URL = "http://10.89.139.9:8080/video"  # !!! IMPORTANT: Replace with your actual IP Webcam URL !!!
MODEL_PATH = "yolov8n.pt"                     # YOLO model (e.g., yolov8n.pt, yolov8s.pt)
CONF_THRESHOLD = 0.4                          # Confidence threshold for detections
BUFFER_SIZE = 1                               # Number of frames to buffer for OpenCV (lower for less latency)

# MQTT Configuration (for sending YOLO alerts)
MQTT_BROKER = '51552d777a9f492cba1b3cc4ef6b37a9.s1.eu.hivemq.cloud' # Your HiveMQ Host
MQTT_PORT = 8883 # 8883 for TLS
MQTT_USERNAME = 'pythontester1'
MQTT_PASSWORD = 'YOUR_MQTT_PASSWORD_HERE'
MQTT_TOPIC_ALERTS = "home/ip_cam/yolo_alerts"
MQTT_CLIENT_ID = "yolo_python_processor_" + str(int(time.time())) # Unique ID

# Flask Configuration (for serving the annotated video stream)
FLASK_HOST = '0.0.0.0' # Listen on all available network interfaces
FLASK_PORT = 5000      # Port for the output stream
OUTPUT_STREAM_RESOLUTION = (640, 480) # Fixed resolution for the output stream

# =========================
# YOLO ALERT DEBOUNCING CONFIG
# =========================
# How long to wait before sending another alert of the *same type* (in seconds)
ALERT_DEBOUNCE_TIME = 10 # seconds
# Store the last time an alert for a specific object type was sent
last_alert_times = {} # Key: label (e.g., 'person'), Value: datetime object

# =========================
# SECURITY SENSITIVE OBJECT FILTER
# =========================
SECURITY_CLASSES = [
    'person',
    'bicycle', 'car', 'motorcycle', 'bus', 'truck', 'train', 'airplane', 'boat',
    'cat', 'dog', 'horse', 'sheep', 'cow', 'bear'
]

# =========================
# MQTT CLIENT SETUP
# =========================
mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, client_id=MQTT_CLIENT_ID)
mqtt_client.username_pw_set(MQTT_USERNAME, MQTT_PASSWORD)

def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print(f"[MQTT] ✅ Connected to MQTT Broker: {MQTT_BROKER}")
    else:
        print(f"[MQTT] ❌ Failed to connect to MQTT Broker, return code {rc}")

try:
    mqtt_client.on_connect = on_connect
    mqtt_client.tls_set() # Enable TLS
    mqtt_client.connect(MQTT_BROKER, MQTT_PORT, 60)
    mqtt_client.loop_start()
except Exception as e:
    print(f"[MQTT] ❌ Error connecting to MQTT Broker: {e}")

# =========================
# LOAD YOLO MODEL
# =========================
try:
    model = YOLO(MODEL_PATH)
    print(f"[YOLO] ✅ Model '{MODEL_PATH}' loaded")

    # --- GPU USAGE ---
    if torch.cuda.is_available():
        model.to('cuda')
        print("[YOLO] Using CUDA (GPU) for inference. 🎉")
    else:
        model.to('cpu')
        print("[YOLO] CUDA not available, falling back to CPU for inference.")
    # --- END OF GPU USAGE ---

except Exception as e:
    print(f"[YOLO] ❌ Error loading YOLOv8 model: {e}")
    exit()

# =========================
# GLOBAL FRAME VARIABLE FOR FLASK STREAMING
# =========================
output_frame = None
lock = threading.Lock()

# =========================
# FLASK APP SETUP
# =========================
app = Flask(__name__)

HTML_PAGE = """
<html>
    <head>
        <title>YOLO Stream (Python Flask)</title>
        <style>body { font-family: sans-serif; text-align: center; background-color: #333; color: #eee; }</style>
    </head>
    <body>
        <h1>Live YOLO Annotated Stream</h1>
        <img src="{{ url_for('video_feed') }}" width="640" height="480" style="border: 2px solid #0f0;">
        <p>This stream is generated by the Python script with YOLO detections (filtered for security classes).</p>
    </body>
</html>
"""

@app.route('/')
def index():
    return render_template_string(HTML_PAGE)

def generate_frames():
    global output_frame
    while True:
        with lock:
            if output_frame is None:
                time.sleep(0.1)
                continue

            ret, buffer = cv2.imencode('.jpg', output_frame, [int(cv2.IMWRITE_JPEG_QUALITY), 90]) # Higher quality
            if not ret:
                continue

            frame_bytes = buffer.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')
        time.sleep(0.03) # Small delay for reasonable frame rate (approx 30 FPS)

@app.route('/video_feed')
def video_feed():
    return Response(generate_frames(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

def run_flask_app():
    app.run(host=FLASK_HOST, port=FLASK_PORT, debug=False, threaded=True)

flask_thread = threading.Thread(target=run_flask_app)
flask_thread.daemon = True
flask_thread.start()
print(f"[Flask] ✅ Server started on http://{FLASK_HOST}:{FLASK_PORT}")
print(f"[Flask]    MJPEG stream available at http://{FLASK_HOST}:{FLASK_PORT}/video_feed")

# =========================
# OPEN IP CAMERA STREAM
# =========================
cap = cv2.VideoCapture(IPCAM_URL, cv2.CAP_FFMPEG)
cap.set(cv2.CAP_PROP_BUFFERSIZE, BUFFER_SIZE)
time.sleep(1)

if not cap.isOpened():
    print(f"[Camera] ❌ Cannot open IP camera stream from {IPCAM_URL}")
    print("         Please check URL, camera app, and network access.")
    exit()

print(f"[Camera] ✅ Stream opened from {IPCAM_URL}")

# =========================
# MAIN VIDEO PROCESSING LOOP
# =========================
while True:
    ret, frame = cap.read()
    if not ret:
        print("[Camera] ⚠️ Frame not received, attempting to re-open stream...")
        cap.release()
        time.sleep(2)
        cap = cv2.VideoCapture(IPCAM_URL, cv2.CAP_FFMPEG)
        cap.set(cv2.CAP_PROP_BUFFERSIZE, BUFFER_SIZE)
        time.sleep(1)
        if not cap.isOpened():
            print("[Camera] ❌ Failed to re-open stream. Exiting.")
            break
        else:
            print("[Camera] ✅ Stream re-opened successfully.")
            continue

    # =========================
    # YOLO INFERENCE
    # =========================
    try:
        # Perform inference on the original frame
        results = model(frame, conf=CONF_THRESHOLD, verbose=False) # verbose=False reduces terminal output
    except Exception as e:
        print(f"[YOLO] ⚠️ Error during inference: {e}. Skipping frame.")
        continue

    # Create a copy for annotation. We only annotate if security objects are found.
    annotated_frame = frame.copy()
    current_detections_for_mqtt = [] # List to store unique detections for this frame, ready for MQTT

    found_security_object = False # Flag to check if any security object was detected

    for r in results:
        boxes = r.boxes
        for box in boxes:
            cls_id = int(box.cls[0])
            label = model.names[cls_id]
            conf = float(box.conf[0])

            # --- ONLY PROCESS IF THE OBJECT IS IN THE SECURITY_CLASSES LIST ---
            if label in SECURITY_CLASSES:
                found_security_object = True
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # Draw bounding box on the annotated frame
                cv2.rectangle(annotated_frame, (x1, y1), (x2, y2), (255,0, 255), 2)
                cv2.putText(
                    annotated_frame,
                    f"{label} {conf:.2f}",
                    (x1, y1 - 8),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.5,
                    (255, 0, 0),
                    2
                )

                # Check for debouncing for this specific label
                now = datetime.now()
                if label not in last_alert_times or (now - last_alert_times[label]).total_seconds() > ALERT_DEBOUNCE_TIME:
                    current_detections_for_mqtt.append({
                        "label": label,
                        "confidence": round(conf, 2),
                        "timestamp": now.isoformat()
                    })
                    last_alert_times[label] = now # Update last alert time for this label

    # =========================
    # MQTT Publishes (Send only if unique new security detections were found)
    # =========================
    if current_detections_for_mqtt:
        # Human-readable payload
        alert_message_parts = []
        for d in current_detections_for_mqtt:
            alert_message_parts.append(f"{d['label']} ({(d['confidence']*100):.0f}%)")
        human_readable_payload = f"SECURITY ALERT: Detected {', '.join(alert_message_parts)}"

        print(f"[MQTT] ⬆️ Publishing alert: {human_readable_payload}")
        try:
            mqtt_client.publish(MQTT_TOPIC_ALERTS, human_readable_payload)
        except Exception as e:
            print(f"[MQTT] ❌ Error publishing MQTT message: {e}")
    # Replace the current publish block with:
# """
# if current_detections_for_mqtt:
#     alert_payload = {
#         "ts": int(time.time()),
#         "source": "vision",
#         "domain": "camera",
#         "entity": "front_door_camera",  # make dynamic later
#         "type": "event",
#         "name": "object_detected",
#         "data": {
#             "objects": [d["label"] for d in current_detections_for_mqtt],
#             "confidences": [d["confidence"] for d in current_detections_for_mqtt],
#             "count": len(current_detections_for_mqtt),
#             "human_readable": f"Detected {len(current_detections_for_mqtt)} security object(s)"
#         },
#         "meta": {"origin": "yolo_processor"}
#     }
#     mqtt_client.publish("event/vision/detection", json.dumps(alert_payload))
#  """
    # =========================
    # UPDATE GLOBAL FRAME FOR FLASK STREAM
    # =========================
    try:
        # If no security objects were found, the annotated_frame is just a copy of the original frame.
        # This ensures the stream always shows video, even if no detections are made.
        ann_resized = cv2.resize(annotated_frame, OUTPUT_STREAM_RESOLUTION)
        with lock:
            output_frame = ann_resized.copy()
    except Exception as e:
        print(f"[Frame] ⚠️ Error preparing frame for streaming: {e}. Skipping update.")
        continue

    # =========================
    # LOCAL DISPLAY (Optional: uncomment to show video locally)
    # =========================
    # cv2.imshow("YOLO Annotated Stream - Press 'q' to exit", annotated_frame)
    # if cv2.waitKey(1) & 0xFF == ord('q'):
    #     break

# =========================
# CLEANUP
# =========================
cap.release()
cv2.destroyAllWindows()
mqtt_client.loop_stop()
mqtt_client.disconnect()
print("Application stopped.")